version: '3.8'

services:
  mysql:
    image: mysql:8.0
    env_file: ./.env
    container_name: sch_rest_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: sch_rest_phpmyadmin
    ports:
      - 8909:80
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=300M
    depends_on:
      - mysql

  server:
    build: .
    container_name: javaapp-sch-restapi
    env_file: ./.env
    ports:
      - "1712:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  db_data:
