spring:
  application:
    name: my-app-sch
  # Jackson
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  # Datasource
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


# Server port Spring
server:
  port: 8080

# Logging
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

security:
  jwt:
    key:
      private: d418227f7d2e81ff37bb952b645ed2444baeb4e16e7913230ece8159842250d1
    user:
      generator: AUTH0JWT_BACKEND
